In [1]:
import pandas as pd
import numpy as np

import sys
import warnings 
if not sys.warnoptions:
    warnings.simplefilter('ignore')

In [2]:
df = pd.read_csv('candidatos.csv')

In [3]:
df.columns

Index(['enrollee_id', 'city', 'city_development_index', 'gender',
       'relevent_experience', 'enrolled_university', 'education_level',
       'major_discipline', 'experience', 'company_size', 'company_type',
       'last_new_job', 'training_hours', 'target'],
      dtype='str')

In [19]:
df = df.rename(
    columns={
        'enrollee_id': 'id', 
        'city': 'cod_cidade', 
        'city_development_index': 'indice_desenv_cidade', 
        'gender': 'sexo',
        'relevent_experience': 'experiencia_relevante?', 
        'enrolled_university': 'curso_universitario_matriculado', 
        'education_level': 'nivel_educacional',
        'major_discipline': 'disciplina_principal', 
        'experience': 'experiencia', 
        'company_size': 'tamanho_empresa', 
        'company_type': 'tipo_empresa',
        'last_new_job': 'diferenca_anos_ultimo_novo_emprego', 
        'training_hours': 'horas_treinamento', 
        'target': 'pretende_trocar_de_emprego?'

    } 
)

In [5]:
df['relevent_experience'].unique()

<StringArray>
['Has relevent experience', 'No relevent experience']
Length: 2, dtype: str

In [6]:
df['relevent_experience'] = df['relevent_experience'].map(
    {
        'Has relevent experience': 'Tem experiencia relevantes',
        'No relevent experience': 'Nao tem exeperiencia relevante'
         }
)

In [7]:
df['relevent_experience'].unique()

<StringArray>
['Tem experiencia relevantes', 'Nao tem exeperiencia relevante']
Length: 2, dtype: str

In [8]:
df.isnull().mean()

enrollee_id               0.000000
city                      0.000000
city_development_index    0.000000
gender                    0.235306
relevent_experience       0.000000
enrolled_university       0.020148
education_level           0.024011
major_discipline          0.146832
experience                0.003393
company_size              0.309949
company_type              0.320493
last_new_job              0.022080
training_hours            0.000000
target                    0.000000
dtype: float64

In [9]:
moda = df['enrolled_university'].mode()[0]

In [10]:
moda

'no_enrollment'

In [11]:
df['enrolled_university'] = df['enrolled_university'].fillna(moda)

In [12]:
df.isnull().mean()

enrollee_id               0.000000
city                      0.000000
city_development_index    0.000000
gender                    0.235306
relevent_experience       0.000000
enrolled_university       0.000000
education_level           0.024011
major_discipline          0.146832
experience                0.003393
company_size              0.309949
company_type              0.320493
last_new_job              0.022080
training_hours            0.000000
target                    0.000000
dtype: float64

In [13]:
# Dados simulados
df_escolas = pd.DataFrame({
    'ID_Escola': [1, 2, 3],
    'Nome_Escola': ['Escola A', 'Escola B', 'Escola C'],
    'Tipo_Escola': ['Publica', 'Privada', 'Publica'],
    'Numero_Alunos': [300, 150, 400],
    'Orcamento_Anual': [500000, 800000, 600000]
})

df_estudantes = pd.DataFrame({
    'ID_Estudante': [101, 102, 103, 104, 105],
    'Nome_Estudante': ['Ana', 'João', 'Carlos', 'Maria', 'Lucia'],
    'Genero': ['F', 'M', 'M', 'F', 'F'],
    'Serie': [1, 2, 1, 3, 2],
    'Nome_Escola': ['Escola A', 'Escola B', 'Escola A', 'Escola C', 'Escola C'],
    'Nota_Redacao': [80, 90, 70, 88, 85],
    'Nota_Matematica': [75, 85, 65, 90, 80]
})

In [14]:
df_escolas

   ID_Escola Nome_Escola Tipo_Escola  Numero_Alunos  Orcamento_Anual
0          1    Escola A     Publica            300           500000
1          2    Escola B     Privada            150           800000
2          3    Escola C     Publica            400           600000

In [15]:
df_estudantes

,ID_Estudante,Nome_Estudante,Genero,Serie,Nome_Escola,Nota_Redacao,Nota_Matematica
0,101,Ana,F,1,Escola A,80,75
1,102,João,M,2,Escola B,90,85
2,103,Carlos,M,1,Escola A,70,65
3,104,Maria,F,3,Escola C,88,90
4,105,Lucia,F,2,Escola C,85,80

In [16]:
df_novo = df_estudantes.merge(df_escolas, left_on='Nome_Escola',
                              right_on='Nome_Escola', how='inner')

In [17]:
df_novo

,ID_Estudante,Nome_Estudante,Genero,Serie,Nome_Escola,Nota_Redacao,Nota_Matematica,ID_Escola,Tipo_Escola,Numero_Alunos,Orcamento_Anual
0,101,Ana,F,1,Escola A,80,75,1,Publica,300,500000
1,102,João,M,2,Escola B,90,85,2,Privada,150,800000
2,103,Carlos,M,1,Escola A,70,65,1,Publica,300,500000
3,104,Maria,F,3,Escola C,88,90,3,Publica,400,600000
4,105,Lucia,F,2,Escola C,85,80,3,Publica,400,600000

In [18]:
df_novo.groupby('Tipo_Escola')[['Nota_Redacao','Nota_Matematica']].mean()

             Nota_Redacao  Nota_Matematica
Tipo_Escola
Privada             90.00             85.0
Publica             80.75             77.5